name: TDD Build Test

on:
  workflow_dispatch: # manuell auslösen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - run: python tdd.py
        env:
          NS_URL: ${{ secrets.NS_URL }}
          NS_SECRET: ${{ secrets.NS_SECRET }}
